### ISSUE TITLE
Build error[E0554]: `#![feature]` may not be used on the stable release channel on latest Rust 1.48.0

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-rs#215]
Win 10

```
C:\Users\xxx>rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```

Log:

```
C:/Users/xxx/.cargo/bin/cargo.exe build --color=always --all --all-targets
   Compiling proc-macro2 v1.0.24
   Compiling winapi v0.3.9
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.54
   Compiling autocfg v1.0.1
   Compiling memchr v2.3.4
   Compiling cfg-if v0.1.10
   Compiling log v0.4.11
   Compiling winapi-build v0.1.1
   Compiling futures-core v0.3.8
   Compiling cache-padded v1.1.1
   Compiling cc v1.0.66
   Compiling futures-io v0.3.8
   Compiling fastrand v1.4.0
   Compiling libc v0.2.81
   Compiling waker-fn v1.1.0
   Compiling parking v2.0.0
   Compiling pin-project-lite v0.2.0
   Compiling winapi v0.2.8
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.5.2
   Compiling async-task v4.0.3
   Compiling vec-arena v1.0.0
   Compiling serde_derive v1.0.118
   Compiling slab v0.4.2
   Compiling event-listener v2.5.1
   Compiling serde v1.0.118
   Compiling atomic-waker v1.0.0
   Compiling cfg-if v1.0.0
   Compiling iovec v0.1.4
   Compiling regex-syntax v0.6.21
   Compiling pin-utils v0.1.0
   Compiling smallvec v1.5.1
   Compiling hashbrown v0.9.1
   Compiling bytes v0.5.6
   Compiling fnv v1.0.7
   Compiling pin-project-lite v0.1.11
   Compiling crossbeam-utils v0.8.1
   Compiling num-traits v0.2.14
   Compiling indexmap v1.6.1
   Compiling ws2_32-sys v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling concurrent-queue v1.2.2
   Compiling wepoll-sys v3.0.1
   Compiling thread_local v1.0.1
   Compiling async-mutex v1.4.0
   Compiling async-channel v1.5.1
   Compiling futures-lite v1.11.3
   Compiling aho-corasick v0.7.15
   Compiling net2 v0.2.37
   Compiling nb-connect v1.0.2
   Compiling socket2 v0.3.18
   Compiling kv-log-macro v1.0.7
   Compiling num_cpus v1.13.0
   Compiling quote v1.0.7
   Compiling async-executor v1.4.0
   Compiling blocking v1.0.2
   Compiling regex v1.4.2
   Compiling miow v0.3.6
   Compiling miow v0.2.2
   Compiling mio v0.6.23
   Compiling polling v2.0.2
   Compiling async-io v1.3.1
   Compiling mio-named-pipes v0.1.7
   Compiling async-global-executor v1.4.3
   Compiling async-attributes v1.1.1
   Compiling thiserror-impl v1.0.22
   Compiling async-trait v0.1.42
   Compiling tokio-macros v0.2.6
   Compiling async-std v1.8.0
   Compiling thiserror v1.0.22
   Compiling tokio v0.2.24
   Compiling rhai v0.18.3
   Compiling casbin v2.0.1 (F:\github_repos\casbin-rs)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> benches\benchmark.rs:1:1
  |
1 | #![feature(test)]
  | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `casbin`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

**Comment by hsluoyz** [comment]
The solution is to use Rust nightly, see: https://stackoverflow.com/questions/48593858/how-to-execute-cargo-test-using-the-nightly-channel

**Comment by Akumar201** [comment]
This error message states, you cannot compile that code with stable Rust. You need to install nightly Rust and then use it to compile the program. You can use the following commands to run the code. 

To install nightly version:
`rustup install nightly`

To set nightly version as default:
`rustup default nightly`

At anytime if you want to switch back to stable Rust:
`rustup default stable`

The nightly version is updated very frequently, so you might want to update it every week or more often. To do so, you need to run this command:
`rustup update`

I am closing this issue as it has been solved. If the problem persists, please comment and the issue will be reopened if appropriate

**Comment by Keon6** [comment]
Still having this issue even after using nightly. But it does seem overriden - active toolchain according to rustup show:

nightly-2022-08-08-aarch64-apple-darwin (overridden by '<directory>/hash-test-drive/apps/engine/rust-toolchain.toml')

**Comment by nobodyguy** [comment]
Relying on unstable API of nightly branch of some language is a terrible approach.

**Comment by hsluoyz** [comment]
@nobodyguy I think this issue has been fixed already long ago?

@MuZhou233 plz double-check

**Comment by MuZhou233** [comment]
To be specific, the feature attributes is removed since v2.0.8. See `benches/benchmark.rs` in https://github.com/casbin/casbin-rs/compare/v2.0.7...v2.0.8
Current build CI uses stable and beta channel and all passed successfully. See https://github.com/casbin/casbin-rs/actions/workflows/ci.yml
